- hosts: wazuh-it-master
  tasks:
   - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
     ansible.builtin.file:
        path: /home/pawelb/ansible
        state: touch
        mode: u=rw,g=r,o=r
